# bash completion for sdl, generated by 'sdl completion bash' from the
# command tree of the generating binary. DO NOT EDIT: the script is
# static, so regenerate it after upgrading sdl.
#
# Wiring (see 'sdl help completion'):
#
#	sdl completion bash > ~/.sdl-completion.bash
#	echo 'source ~/.sdl-completion.bash' >> ~/.bashrc

# _sdl_reply offers the candidate words that match the word under the
# cursor.
_sdl_reply() {
	COMPREPLY=($(compgen -W "$*" -- "$cur"))
}

_sdl() {
	local cur=${COMP_WORDS[COMP_CWORD]}
	COMPREPLY=()
	if [ "$COMP_CWORD" -eq 1 ]; then
		_sdl_reply build completion echo fmt help highlight image run
		return
	fi
	case ${COMP_WORDS[1]} in
	build) _sdl_build ;;
	completion) _sdl_completion ;;
	fmt) _sdl_fmt ;;
	help) _sdl_help ;;
	highlight) _sdl_highlight ;;
	image) _sdl_image ;;
	run) _sdl_run ;;
	esac
}

# sdl build
_sdl_build() {
	case $cur in
	-*) _sdl_reply -generation -o -work ;;
	esac
}

# sdl completion
_sdl_completion() {
	if [ "$COMP_CWORD" -eq 2 ]; then
		_sdl_reply bash zsh
	fi
}

# sdl fmt
_sdl_fmt() {
	case $cur in
	-*) _sdl_reply -d -l -w ;;
	esac
}

# sdl highlight
_sdl_highlight() {
	if [ "$COMP_CWORD" -eq 2 ]; then
		_sdl_reply vim vscode
	fi
}

# sdl image
_sdl_image() {
	if [ "$COMP_CWORD" -eq 2 ]; then
		_sdl_reply edit info records symbols
		return
	fi
	case ${COMP_WORDS[2]} in
	edit) _sdl_image_edit ;;
	esac
}

# sdl image edit
_sdl_image_edit() {
	case $cur in
	-*) _sdl_reply -generation ;;
	esac
}

# sdl run
_sdl_run() {
	case $cur in
	-*) _sdl_reply -extern -grace -work ;;
	esac
}

# sdl help
_sdl_help() {
	if [ "$COMP_CWORD" -eq 2 ]; then
		_sdl_reply build completion echo fmt highlight image run
		return
	fi
	case ${COMP_WORDS[2]} in
	image) _sdl_help_image ;;
	esac
}

# sdl help image
_sdl_help_image() {
	if [ "$COMP_CWORD" -eq 3 ]; then
		_sdl_reply edit info records symbols
	fi
}

# Filename completion is the fallback wherever the tree offers no
# words (-o default): solution directories, image files.
complete -o default -F _sdl sdl
