#compdef sdl
# zsh completion for sdl, generated by 'sdl completion zsh' from the
# command tree of the generating binary. DO NOT EDIT: the script is
# static, so regenerate it after upgrading sdl.
#
# Install as _sdl in any $fpath directory for compinit to find, or
# source it directly after compinit has run (see 'sdl help
# completion').

_sdl() {
	if (( CURRENT == 2 )); then
		local -a commands
		commands=(
			'build:compile a solution directory into its desired-state image'
			'completion:emit a shell completion script for the sdl command'
			'echo:render a desired-state image as canonical SDL'
			'fmt:reformat solution units in canonical form'
			'help:show documentation for a command'
			'highlight:emit an editor syntax definition for solution units'
			'image:amend and query desired-state image files'
			'run:compile and run a solution in a tailored host process'
			'vet:report likely mistakes in solution units'
		)
		_describe -t commands 'sdl command' commands
		return
	fi
	case $words[2] in
	build) shift words; (( CURRENT-- )); _sdl_build ;;
	completion) shift words; (( CURRENT-- )); _sdl_completion ;;
	echo) shift words; (( CURRENT-- )); _sdl_echo ;;
	fmt) shift words; (( CURRENT-- )); _sdl_fmt ;;
	help) shift words; (( CURRENT-- )); _sdl_help ;;
	highlight) shift words; (( CURRENT-- )); _sdl_highlight ;;
	image) shift words; (( CURRENT-- )); _sdl_image ;;
	run) shift words; (( CURRENT-- )); _sdl_run ;;
	vet) shift words; (( CURRENT-- )); _sdl_vet ;;
	esac
}

# sdl build
_sdl_build() {
	_arguments \
		'-generation[stamp the image with generation N]:N' \
		'-o[write the image to file instead of stdout]:file:_files' \
		'-work[print the work directory and do not delete it]' \
		'*:file:_files'
}

# sdl completion
_sdl_completion() {
	_arguments ':argument:(bash zsh)'
}

# sdl echo
_sdl_echo() {
	_arguments '*:file:_files'
}

# sdl fmt
_sdl_fmt() {
	_arguments \
		'-d[display diffs instead of rewriting files]' \
		'-l[list files whose formatting differs]' \
		'-w[write the canonical form back to the files]' \
		'*:file:_files'
}

# sdl highlight
_sdl_highlight() {
	_arguments ':argument:(vim vscode)'
}

# sdl image
_sdl_image() {
	if (( CURRENT == 2 )); then
		local -a commands
		commands=(
			'edit:amend an image file in place'
			'info:print an image'\''s identity and provenance'
			'records:list an image'\''s records as a table'
			'symbols:list an image'\''s symbol table as a table'
		)
		_describe -t commands 'sdl image command' commands
		return
	fi
	case $words[2] in
	edit) shift words; (( CURRENT-- )); _sdl_image_edit ;;
	info) shift words; (( CURRENT-- )); _sdl_image_info ;;
	records) shift words; (( CURRENT-- )); _sdl_image_records ;;
	symbols) shift words; (( CURRENT-- )); _sdl_image_symbols ;;
	esac
}

# sdl image edit
_sdl_image_edit() {
	_arguments \
		'-generation[stamp the image with generation N]:N' \
		'*:file:_files'
}

# sdl image info
_sdl_image_info() {
	_arguments '*:file:_files'
}

# sdl image records
_sdl_image_records() {
	_arguments '*:file:_files'
}

# sdl image symbols
_sdl_image_symbols() {
	_arguments '*:file:_files'
}

# sdl run
_sdl_run() {
	_arguments \
		'*-extern[bind one extern symbol as name=value (repeatable)]:name=value' \
		'-grace[graceful-shutdown budget after the first signal]:duration' \
		'-work[print the work directory and do not delete it]' \
		'*:file:_files'
}

# sdl vet
_sdl_vet() {
	_arguments '*:file:_files'
}

# sdl help
_sdl_help() {
	if (( CURRENT == 2 )); then
		local -a commands
		commands=(
			'build:compile a solution directory into its desired-state image'
			'completion:emit a shell completion script for the sdl command'
			'echo:render a desired-state image as canonical SDL'
			'fmt:reformat solution units in canonical form'
			'highlight:emit an editor syntax definition for solution units'
			'image:amend and query desired-state image files'
			'run:compile and run a solution in a tailored host process'
			'vet:report likely mistakes in solution units'
		)
		_describe -t commands 'sdl help topic' commands
		return
	fi
	case $words[2] in
	image) shift words; (( CURRENT-- )); _sdl_help_image ;;
	esac
}

# sdl help image
_sdl_help_image() {
	if (( CURRENT == 2 )); then
		local -a commands
		commands=(
			'edit:amend an image file in place'
			'info:print an image'\''s identity and provenance'
			'records:list an image'\''s records as a table'
			'symbols:list an image'\''s symbol table as a table'
		)
		_describe -t commands 'sdl help topic' commands
		return
	fi
}

# The autoload form doubles as a sourceable script: compinit runs the
# file as the _sdl function itself, and a direct source registers the
# completer instead.
if [ "$funcstack[1]" = "_sdl" ]; then
	_sdl "$@"
else
	compdef _sdl sdl
fi
