// Copyright 2026 The prototype authors. Use of this source code is
// governed by the license that can be found in the LICENSE file.

package completioncmd

import (
	"bytes"
	"fmt"
	"io"
	"strings"
)

// emitBash renders the tree as a bash completion script: one shell
// function per command path, dispatching on the same fixed word
// positions the sdl dispatcher reads — the verb is always word 1, a
// group's subcommand the word right after the group — which holds
// because flags only ever follow the full command path. Commands with
// nothing to offer get no function at all: the script leaves COMPREPLY
// empty there and the -o default registration falls back to the
// shell's own filename completion, which is what the file and
// directory arguments want. The constructs stay within bash 3.2 (the
// macOS system bash): plain arrays, no compopt.
func emitBash(w io.Writer, cmds []spec) error {
	var b bytes.Buffer
	p := func(format string, args ...any) {
		fmt.Fprintf(&b, format, args...)
		b.WriteByte('\n')
	}

	p("# bash completion for sdl, generated by 'sdl completion bash' from the")
	p("# command tree of the generating binary. DO NOT EDIT: the script is")
	p("# static, so regenerate it after upgrading sdl.")
	p("#")
	p("# Wiring (see 'sdl help completion'):")
	p("#")
	p("#\tsdl completion bash > ~/.sdl-completion.bash")
	p("#\techo 'source ~/.sdl-completion.bash' >> ~/.bashrc")
	p("")
	p("# _sdl_reply offers the candidate words that match the word under the")
	p("# cursor.")
	p("_sdl_reply() {")
	p("\tCOMPREPLY=($(compgen -W \"$*\" -- \"$cur\"))")
	p("}")
	p("")
	p("_sdl() {")
	p("\tlocal cur=${COMP_WORDS[COMP_CWORD]}")
	p("\tCOMPREPLY=()")
	p("\tif [ \"$COMP_CWORD\" -eq 1 ]; then")
	p("\t\t_sdl_reply %s", strings.Join(withHelp(names(cmds)), " "))
	p("\t\treturn")
	p("\tfi")
	p("\tcase ${COMP_WORDS[1]} in")
	for _, arm := range bashArms(nil, cmds, true) {
		p("\t%s) %s ;;", arm.name, arm.fn)
	}
	p("\tesac")
	p("}")

	var walk func(path []string, specs []spec)
	walk = func(path []string, specs []spec) {
		for _, s := range specs {
			full := append(append([]string{}, path...), s.name)
			if len(s.subs) > 0 {
				emitBashGroup(p, full, s)
				walk(full, s.subs)
				continue
			}
			if len(s.flags) > 0 || len(s.words) > 0 {
				emitBashLeaf(p, full, s)
			}
		}
	}
	walk(nil, cmds)
	emitBashHelp(p, nil, cmds)

	p("")
	p("# Filename completion is the fallback wherever the tree offers no")
	p("# words (-o default): solution directories, image files.")
	p("complete -o default -F _sdl sdl")

	_, err := w.Write(b.Bytes())
	return err
}

// A bashArm is one dispatch arm of a case statement over a command
// word.
type bashArm struct {
	name string // the dispatch word
	fn   string // the function completing under it
}

// bashArms lists the dispatch arms a level emits: one per subcommand
// with anything to offer, plus — at the top level, where root is true
// — the dispatcher's help verb at its alphabetical slot.
func bashArms(path []string, specs []spec, root bool) []bashArm {
	help := bashArm{"help", fname([]string{"help"})}
	var arms []bashArm
	placed := !root
	for _, s := range specs {
		if !placed && s.name > help.name {
			arms = append(arms, help)
			placed = true
		}
		if len(s.subs) == 0 && len(s.flags) == 0 && len(s.words) == 0 {
			continue
		}
		full := append(append([]string{}, path...), s.name)
		arms = append(arms, bashArm{s.name, fname(full)})
	}
	if !placed {
		arms = append(arms, help)
	}
	return arms
}

// emitBashGroup emits the function completing a command group: the
// subcommand words at the group's own argument position, then
// dispatch one level down.
func emitBashGroup(p func(string, ...any), path []string, s spec) {
	p("")
	p("# sdl %s", strings.Join(path, " "))
	p("%s() {", fname(path))
	p("\tif [ \"$COMP_CWORD\" -eq %d ]; then", len(path)+1)
	p("\t\t_sdl_reply %s", strings.Join(names(s.subs), " "))
	p("\t\treturn")
	p("\tfi")
	if arms := bashArms(path, s.subs, false); len(arms) > 0 {
		p("\tcase ${COMP_WORDS[%d]} in", len(path)+1)
		for _, arm := range arms {
			p("\t%s) %s ;;", arm.name, arm.fn)
		}
		p("\tesac")
	}
	p("}")
}

// emitBashLeaf emits the function completing a runnable command's
// flags and enumerated first argument. Only called when there is
// something to offer; file arguments ride the -o default fallback.
func emitBashLeaf(p func(string, ...any), path []string, s spec) {
	p("")
	p("# sdl %s", strings.Join(path, " "))
	p("%s() {", fname(path))
	var flags []string
	for _, f := range s.flags {
		flags = append(flags, "-"+f.name)
	}
	wordsIf := func(indent string) {
		p("%sif [ \"$COMP_CWORD\" -eq %d ]; then", indent, len(path)+1)
		p("%s\t_sdl_reply %s", indent, strings.Join(s.words, " "))
		p("%sfi", indent)
	}
	switch {
	case len(flags) > 0 && len(s.words) > 0:
		p("\tcase $cur in")
		p("\t-*) _sdl_reply %s ;;", strings.Join(flags, " "))
		p("\t*)")
		wordsIf("\t\t")
		p("\t\t;;")
		p("\tesac")
	case len(flags) > 0:
		p("\tcase $cur in")
		p("\t-*) _sdl_reply %s ;;", strings.Join(flags, " "))
		p("\tesac")
	default:
		wordsIf("\t")
	}
	p("}")
}

// emitBashHelp emits the help-topic functions: 'sdl help' completes
// registered command paths as topics — names only, walking groups the
// way the help implementation itself does, and never offering help as
// its own topic.
func emitBashHelp(p func(string, ...any), path []string, specs []spec) {
	full := append([]string{"help"}, path...)
	p("")
	p("# sdl %s", strings.Join(full, " "))
	p("%s() {", fname(full))
	p("\tif [ \"$COMP_CWORD\" -eq %d ]; then", len(full)+1)
	p("\t\t_sdl_reply %s", strings.Join(names(specs), " "))
	if len(groups(specs)) == 0 {
		p("\tfi")
		p("}")
		return
	}
	p("\t\treturn")
	p("\tfi")
	p("\tcase ${COMP_WORDS[%d]} in", len(full)+1)
	for _, s := range groups(specs) {
		sub := append(append([]string{}, full...), s.name)
		p("\t%s) %s ;;", s.name, fname(sub))
	}
	p("\tesac")
	p("}")
	for _, s := range groups(specs) {
		emitBashHelp(p, append(append([]string{}, path...), s.name), s.subs)
	}
}

// groups filters specs down to the command groups; help descends only
// through those.
func groups(specs []spec) []spec {
	var list []spec
	for _, s := range specs {
		if len(s.subs) > 0 {
			list = append(list, s)
		}
	}
	return list
}
