// Copyright 2026 The prototype authors. Use of this source code is
// governed by the license that can be found in the LICENSE file.

package completioncmd

import (
	"bytes"
	"fmt"
	"io"
	"strings"
)

// emitZsh renders the tree as a zsh completion function in compinit's
// autoload form: #compdef on line one, one function per command path.
// Groups descend the way hand-written completers do — shift words,
// decrement CURRENT — so every function sees its own command at
// words[1] and the leaves can hand their surfaces to _arguments
// unadjusted. Command words complete through _describe, which shows
// each command's one-line description beside it; flag descriptions
// ride _arguments the same way.
func emitZsh(w io.Writer, cmds []spec) error {
	var b bytes.Buffer
	p := func(format string, args ...any) {
		fmt.Fprintf(&b, format, args...)
		b.WriteByte('\n')
	}

	p("#compdef sdl")
	p("# zsh completion for sdl, generated by 'sdl completion zsh' from the")
	p("# command tree of the generating binary. DO NOT EDIT: the script is")
	p("# static, so regenerate it after upgrading sdl.")
	p("#")
	p("# Install as _sdl in any $fpath directory for compinit to find, or")
	p("# source it directly after compinit has run (see 'sdl help")
	p("# completion').")
	p("")
	p("_sdl() {")
	emitZshDescribe(p, "sdl command", zshItems(cmds, true))
	p("\tcase $words[2] in")
	placed := false
	arm := func(name string) {
		p("\t%s) shift words; (( CURRENT-- )); %s ;;", name, fname([]string{name}))
	}
	for _, s := range cmds {
		if !placed && s.name > "help" {
			arm("help")
			placed = true
		}
		arm(s.name)
	}
	if !placed {
		arm("help")
	}
	p("\tesac")
	p("}")

	var walk func(path []string, specs []spec)
	walk = func(path []string, specs []spec) {
		for _, s := range specs {
			full := append(append([]string{}, path...), s.name)
			if len(s.subs) > 0 {
				emitZshGroup(p, full, s)
				walk(full, s.subs)
				continue
			}
			emitZshLeaf(p, full, s)
		}
	}
	walk(nil, cmds)
	emitZshHelp(p, nil, cmds)

	p("")
	p("# The autoload form doubles as a sourceable script: compinit runs the")
	p("# file as the _sdl function itself, and a direct source registers the")
	p("# completer instead.")
	p("if [ \"$funcstack[1]\" = \"_sdl\" ]; then")
	p("\t_sdl \"$@\"")
	p("else")
	p("\tcompdef _sdl sdl")
	p("fi")

	_, err := w.Write(b.Bytes())
	return err
}

// emitZshDescribe emits the head of a group function: when the cursor
// sits on the group's own argument word — always words[2], every
// function having shifted itself to words[1] — describe the candidate
// command words and return.
func emitZshDescribe(p func(string, ...any), label string, items []string) {
	p("\tif (( CURRENT == 2 )); then")
	p("\t\tlocal -a commands")
	p("\t\tcommands=(")
	for _, item := range items {
		p("\t\t\t%s", item)
	}
	p("\t\t)")
	p("\t\t_describe -t commands %s commands", zsq(label))
	p("\t\treturn")
	p("\tfi")
}

// zshItems renders the name:description pairs _describe takes. At the
// top level — root true — the dispatcher's help verb joins at its
// alphabetical slot.
func zshItems(specs []spec, root bool) []string {
	help := zsq("help:show documentation for a command")
	var items []string
	placed := !root
	for _, s := range specs {
		if !placed && s.name > "help" {
			items = append(items, help)
			placed = true
		}
		item := s.name
		if s.short != "" {
			item += ":" + s.short
		}
		items = append(items, zsq(item))
	}
	if !placed {
		items = append(items, help)
	}
	return items
}

// emitZshGroup emits the function completing a command group.
func emitZshGroup(p func(string, ...any), path []string, s spec) {
	p("")
	p("# sdl %s", strings.Join(path, " "))
	p("%s() {", fname(path))
	emitZshDescribe(p, "sdl "+strings.Join(path, " ")+" command", zshItems(s.subs, false))
	p("\tcase $words[2] in")
	for _, sub := range s.subs {
		full := append(append([]string{}, path...), sub.name)
		p("\t%s) shift words; (( CURRENT-- )); %s ;;", sub.name, fname(full))
	}
	p("\tesac")
	p("}")
}

// emitZshLeaf emits the function completing a runnable command: its
// flag surface and positional shape as one _arguments call, or a
// bare message when the command takes nothing at all.
func emitZshLeaf(p func(string, ...any), path []string, s spec) {
	p("")
	p("# sdl %s", strings.Join(path, " "))
	p("%s() {", fname(path))
	var specs []string
	for _, f := range s.flags {
		specs = append(specs, zshFlagSpec(f))
	}
	if len(s.words) > 0 {
		specs = append(specs, zsq(":argument:("+strings.Join(s.words, " ")+")"))
	}
	if s.files {
		specs = append(specs, zsq("*:file:_files"))
	}
	switch {
	case len(specs) == 0:
		p("\t_message 'no arguments'")
	case len(specs) == 1:
		p("\t_arguments %s", specs[0])
	default:
		p("\t_arguments \\")
		for i, sp := range specs {
			cont := " \\"
			if i == len(specs)-1 {
				cont = ""
			}
			p("\t\t%s%s", sp, cont)
		}
	}
	p("}")
}

// zshFlagSpec renders one flag as an _arguments spec: description in
// brackets, then the value's placeholder as the message for non-
// boolean flags. A placeholder named file gets _files, the one
// placeholder with an obvious completion; the rest complete nothing
// and show the placeholder. Flags whose usage advertises
// "(repeatable)" take the * prefix so the shell offers them again.
func zshFlagSpec(f flagSpec) string {
	var sb strings.Builder
	if f.repeats {
		sb.WriteString("*")
	}
	sb.WriteString("-")
	sb.WriteString(f.name)
	sb.WriteString("[")
	sb.WriteString(zdesc(f.usage))
	sb.WriteString("]")
	if !f.boolean {
		sb.WriteString(":")
		sb.WriteString(zmsg(f.arg))
		if f.arg == "file" {
			sb.WriteString(":_files")
		}
	}
	return zsq(sb.String())
}

// emitZshHelp emits the help-topic functions: names only, described,
// descending through groups the way the help implementation does,
// never offering help as its own topic.
func emitZshHelp(p func(string, ...any), path []string, specs []spec) {
	full := append([]string{"help"}, path...)
	p("")
	p("# sdl %s", strings.Join(full, " "))
	p("%s() {", fname(full))
	emitZshDescribe(p, "sdl help topic", zshItems(specs, false))
	if len(groups(specs)) > 0 {
		p("\tcase $words[2] in")
		for _, s := range groups(specs) {
			sub := append(append([]string{}, full...), s.name)
			p("\t%s) shift words; (( CURRENT-- )); %s ;;", s.name, fname(sub))
		}
		p("\tesac")
	}
	p("}")
	for _, s := range groups(specs) {
		emitZshHelp(p, append(append([]string{}, path...), s.name), s.subs)
	}
}

// zsq renders s as one single-quoted zsh word.
func zsq(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// zdesc escapes s for the inside of an _arguments [description].
func zdesc(s string) string {
	return strings.NewReplacer(`\`, `\\`, `[`, `\[`, `]`, `\]`).Replace(s)
}

// zmsg escapes s for an _arguments :message field.
func zmsg(s string) string {
	return strings.NewReplacer(`\`, `\\`, `:`, `\:`).Replace(s)
}
