" Vim syntax file for SDL, the solution definition language.
" Generated by sdl highlight vim from the toolchain's grammar code;
" regenerate instead of editing, or the file drifts from the grammar.

if exists("b:current_syntax")
  finish
endif

syn case match

" Keywords and boolean literals (sdl/token).
syn keyword sdlKeyword as default deploy extern import provision solution var
syn keyword sdlBoolean false true

" Body vocabulary (solution.Vocabulary): the section words a body may
" open — optionally carrying a dotted qualifier, as in with k8s.pod —
" and the statement verbs' closed top-level fields. Contextual words,
" not reserved ones; coloring them wherever they appear in word
" position is the approximation a regex highlighter affords.
syn keyword sdlSection metadata params with
syn match sdlQualifier /\<\%(metadata\|params\|with\)\s\+\zs\h\w*\%(\.\h\w*\)*/
syn match sdlField /\<\%(location\)\>\ze\s*:/

" Punctuation (sdl/token).
syn match sdlOperator /[{}():.]/

" Literal shapes (sdl/scanner); identifiers deliberately stay plain.
" Durations are defined after integers: where both match at one
" position, Vim gives the later definition priority.
syn match sdlInt /[+-]\=\<\d\+\>/
syn match sdlDuration /[+-]\=\<\d\+[.A-Za-z_][.0-9A-Za-z_]*/
syn region sdlString start=/"/ skip=/\\./ end=/"/ oneline contains=sdlEscape,sdlEscapeError
syn match sdlEscapeError /\\./ contained
syn match sdlEscape /\\[abfnrtv\\"]/ contained
syn match sdlEscape /\\[0-7]\{3}/ contained
syn match sdlEscape /\\x\x\{2}/ contained
syn match sdlEscape /\\u\x\{4}/ contained
syn match sdlEscape /\\U\x\{8}/ contained
syn match sdlComment "//.*$"

hi def link sdlKeyword Keyword
hi def link sdlBoolean Boolean
hi def link sdlSection Structure
hi def link sdlQualifier Type
hi def link sdlField Special
hi def link sdlOperator Delimiter
hi def link sdlInt Number
hi def link sdlDuration Number
hi def link sdlString String
hi def link sdlEscape SpecialChar
hi def link sdlEscapeError Error
hi def link sdlComment Comment

let b:current_syntax = "sdl"
