// Copyright 2026 The prototype authors. Use of this source code is
// governed by the license that can be found in the LICENSE file.

package highlightcmd

import (
	"bytes"
	"fmt"
	"io"
	"strings"
)

// vimLiterals records the Vim rendering decided for every literal
// token: the syntax group that colors it, or "" where the literal
// deliberately stays plain text. checkLiterals holds the emitter to
// this table's completeness.
var vimLiterals = map[string]string{
	"IDENT":    "", // references and keys stay plain
	"STRING":   "sdlString",
	"INT":      "sdlInt",
	"DURATION": "sdlDuration",
}

// emitVim renders the grammar as a Vim syntax file. The word lists
// come straight from the grammar value; the literal shapes are this
// emitter's transcription of the scanner's lexical rules
// (sdl/scanner), ASCII-approximated where the scanner accepts Unicode
// letters.
func emitVim(w io.Writer, g grammar) error {
	if err := checkLiterals("vim", vimLiterals); err != nil {
		return err
	}
	class, err := charClass(g.operators)
	if err != nil {
		return fmt.Errorf("vim: %v", err)
	}

	var b bytes.Buffer
	line := func(s string) {
		b.WriteString(s)
		b.WriteByte('\n')
	}
	line(`" Vim syntax file for SDL, the solution definition language.`)
	line(`" Generated by sdl highlight vim from the toolchain's grammar code;`)
	line(`" regenerate instead of editing, or the file drifts from the grammar.`)
	line(``)
	line(`if exists("b:current_syntax")`)
	line(`  finish`)
	line(`endif`)
	line(``)
	line(`syn case match`)
	line(``)
	line(`" Keywords and boolean literals (sdl/token).`)
	if len(g.keywords) > 0 {
		line(`syn keyword sdlKeyword ` + strings.Join(g.keywords, " "))
	}
	if len(g.booleans) > 0 {
		line(`syn keyword sdlBoolean ` + strings.Join(g.booleans, " "))
	}
	line(``)
	line(`" Body vocabulary (solution.Vocabulary): the section words a body may`)
	line(`" open — optionally carrying a dotted qualifier, as in with k8s.pod —`)
	line(`" and the statement verbs' closed top-level fields. Contextual words,`)
	line(`" not reserved ones; coloring them wherever they appear in word`)
	line(`" position is the approximation a regex highlighter affords.`)
	if len(g.sections) > 0 {
		alt := strings.Join(g.sections, `\|`)
		line(`syn keyword sdlSection ` + strings.Join(g.sections, " "))
		line(`syn match sdlQualifier /\<\%(` + alt + `\)\s\+\zs\h\w*\%(\.\h\w*\)*/`)
	}
	if len(g.fields) > 0 {
		line(`syn match sdlField /\<\%(` + strings.Join(g.fields, `\|`) + `\)\>\ze\s*:/`)
	}
	line(``)
	line(`" Punctuation (sdl/token).`)
	if class != "" {
		line(`syn match sdlOperator /[` + class + `]/`)
	}
	line(``)
	line(`" Literal shapes (sdl/scanner); identifiers deliberately stay plain.`)
	line(`" Durations are defined after integers: where both match at one`)
	line(`" position, Vim gives the later definition priority.`)
	line(`syn match sdlInt /[+-]\=\<\d\+\>/`)
	line(`syn match sdlDuration /[+-]\=\<\d\+[.A-Za-z_][.0-9A-Za-z_]*/`)
	line(`syn region sdlString start=/"/ skip=/\\./ end=/"/ oneline contains=sdlEscape,sdlEscapeError`)
	line(`syn match sdlEscapeError /\\./ contained`)
	line(`syn match sdlEscape /\\[abfnrtv\\"]/ contained`)
	line(`syn match sdlEscape /\\[0-7]\{3}/ contained`)
	line(`syn match sdlEscape /\\x\x\{2}/ contained`)
	line(`syn match sdlEscape /\\u\x\{4}/ contained`)
	line(`syn match sdlEscape /\\U\x\{8}/ contained`)
	line(`syn match sdlComment "//.*$"`)
	line(``)
	line(`hi def link sdlKeyword Keyword`)
	line(`hi def link sdlBoolean Boolean`)
	line(`hi def link sdlSection Structure`)
	line(`hi def link sdlQualifier Type`)
	line(`hi def link sdlField Special`)
	line(`hi def link sdlOperator Delimiter`)
	line(`hi def link sdlInt Number`)
	line(`hi def link sdlDuration Number`)
	line(`hi def link sdlString String`)
	line(`hi def link sdlEscape SpecialChar`)
	line(`hi def link sdlEscapeError Error`)
	line(`hi def link sdlComment Comment`)
	line(``)
	line(`let b:current_syntax = "sdl"`)

	_, err = w.Write(b.Bytes())
	return err
}
