// Copyright 2026 The prototype authors. Use of this source code is
// governed by the license that can be found in the LICENSE file.

package main

import (
	"fmt"
	"go/format"
	"path"
	"sort"
	"strconv"
	"strings"

	"github.com/modern-engineering/prototype/fieldcase/host"
	"github.com/modern-engineering/prototype/solution/image"
)

// The packages every generated host links besides the catalogue.
const (
	hostPkg   = "github.com/modern-engineering/prototype/fieldcase/host"
	driverPkg = "github.com/modern-engineering/prototype/fieldcase/host/driver"
)

// devDrivers maps a provision element's name to the dev driver the
// generated host wires in. Anything else has no driver yet: real
// driver authorship is the A-11 door, deliberately left open.
var devDrivers = map[string]string{
	"Kafka":    "driver.DevKafka{}",
	"Redis":    "driver.DevRedis{}",
	"Neo4j":    "driver.DevNeo4j{}",
	"Postgres": "driver.DevPostgres{}",
}

// generateHost emits the host program: one main.go baking the image's
// records into a host.Config. Site values are NOT baked — the host
// reads site files given as arguments at startup, so one binary serves
// every site and no credential ever reaches generated source.
func generateHost(m *model) (map[string][]byte, error) {
	var b strings.Builder
	fmt.Fprintf(&b, `// Code generated by fieldcase-gen; DO NOT EDIT.

// The %[1]s host: a single process running every deploy record of the
// %[1]s solution image (generation %[2]d), on the fieldcase host engine.
// Run it with one or more site files as arguments; see the engine's
// package documentation for the flag, env, and exit-code contract.
package main

import (
	"os"

`, m.img.Solution, m.img.Generation)

	// Imports: the catalogue packages the deploy records reference
	// (linking is what makes Make reachable), then the engine.
	refs := make(map[string]bool)
	for _, ref := range m.instRef {
		refs[ref.Package] = true
	}
	paths := make([]string, 0, len(refs))
	for p := range refs {
		paths = append(paths, p)
	}
	sort.Strings(paths)
	for _, p := range paths {
		if name := m.pkgName[p]; name != path.Base(p) {
			fmt.Fprintf(&b, "\t%s %q\n", name, p)
		} else {
			fmt.Fprintf(&b, "\t%q\n", p)
		}
	}
	b.WriteString("\n")
	fmt.Fprintf(&b, "\t%q\n", hostPkg)
	if len(m.cfg.Provisions) > 0 {
		fmt.Fprintf(&b, "\t%q\n", driverPkg)
	}
	b.WriteString(")\n\n")

	b.WriteString("func main() {\n\tos.Exit(host.Main(config()))\n}\n\n")
	b.WriteString("// config is the baked desired state: the image's symbol table and\n")
	b.WriteString("// records, in image order, wired to the catalogue descriptors and\n")
	b.WriteString("// the dev provision drivers.\n")
	b.WriteString("func config() *host.Config {\n\treturn &host.Config{\n")
	fmt.Fprintf(&b, "\t\tSolution: %q,\n", m.cfg.Solution)

	b.WriteString("\t\tSymbols: []host.Symbol{\n")
	for _, s := range m.cfg.Symbols {
		fmt.Fprintf(&b, "\t\t\t{Name: %q, Class: %s", s.Name, classExpr(s.Class))
		if s.Type != "" {
			fmt.Fprintf(&b, ", Type: %q", s.Type)
		}
		if s.Sensitive {
			b.WriteString(", Sensitive: true")
		}
		if s.Class == host.ClassVar {
			fmt.Fprintf(&b, ", Default: %q", s.Default)
		}
		b.WriteString("},\n")
	}
	b.WriteString("\t\t},\n")

	if len(m.cfg.Provisions) > 0 {
		b.WriteString("\t\tProvisions: []host.Provision{\n")
		for _, p := range m.cfg.Provisions {
			drv, ok := devDrivers[elementName(p.Type)]
			if !ok {
				return nil, fmt.Errorf("provision %s: no driver for %s (driver authorship is the open A-11 door)", p.Name, p.Type)
			}
			fmt.Fprintf(&b, "\t\t\t{\n\t\t\t\tName: %q, Type: %q, Kind: %q,\n", p.Name, p.Type, p.Kind)
			writeBindings(&b, "Params", p.Params)
			b.WriteString("\t\t\t\tOutputs: []host.Output{")
			for i, out := range p.Outputs {
				if i > 0 {
					b.WriteString(", ")
				}
				fmt.Fprintf(&b, "{Name: %q", out.Name)
				if out.Sensitive {
					b.WriteString(", Sensitive: true")
				}
				b.WriteString("}")
			}
			b.WriteString("},\n")
			fmt.Fprintf(&b, "\t\t\t\tDriver: %s,\n\t\t\t},\n", drv)
		}
		b.WriteString("\t\t},\n")
	}

	b.WriteString("\t\tInstances: []host.Instance{\n")
	for _, inst := range m.cfg.Instances {
		ref := m.instRef[inst.Name]
		fmt.Fprintf(&b, "\t\t\t{\n\t\t\t\tName: %q,\n\t\t\t\tApp: %s.%s,\n", inst.Name, m.pkgName[ref.Package], ref.Name)
		writeBindings(&b, "Params", inst.Params)
		b.WriteString("\t\t\t},\n")
	}
	b.WriteString("\t\t},\n\t}\n}\n")

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("formatting the generated host: %v", err)
	}
	return map[string][]byte{"main.go": src}, nil
}

// writeBindings emits one []host.Binding literal field.
func writeBindings(b *strings.Builder, field string, bindings []host.Binding) {
	if len(bindings) == 0 {
		return
	}
	fmt.Fprintf(b, "\t\t\t\t%s: []host.Binding{\n", field)
	for _, bd := range bindings {
		fmt.Fprintf(b, "\t\t\t\t\t{Key: %q, ", bd.Key)
		switch bd.Kind {
		case host.BindLiteral:
			fmt.Fprintf(b, "Kind: host.BindLiteral, Value: %q", bd.Value)
		case host.BindSymbol:
			fmt.Fprintf(b, "Kind: host.BindSymbol, Value: %q", bd.Value)
		case host.BindOutput:
			fmt.Fprintf(b, "Kind: host.BindOutput, Instance: %q, Output: %q", bd.Instance, bd.Output)
		}
		if bd.Sensitive {
			b.WriteString(", Sensitive: true")
		}
		fmt.Fprintf(b, ", Source: %q},\n", bd.Source)
	}
	b.WriteString("\t\t\t\t},\n")
}

// classExpr names the host constant for a symbol class, keeping the
// generated source readable.
func classExpr(class string) string {
	switch class {
	case image.ClassExtern:
		return "host.ClassExtern"
	case image.ClassVar:
		return "host.ClassVar"
	}
	return strconv.Quote(class)
}

// elementName strips the package half of a display name
// ("substrate.Kafka" -> "Kafka").
func elementName(display string) string {
	if i := strings.LastIndexByte(display, '.'); i >= 0 {
		return display[i+1:]
	}
	return display
}
