apiVersion: v1
kind: ConfigMap
metadata:
  name: observation-translator-cm
  labels:
    app: observation-translator
    solution: anomaly
data:
  health: ":3000"
  observationTranslator: "true"
  site.conf: |
    extern.kafkaCluster = localhost:9092
    driver.kafka.brokers = localhost:9092
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: observation-translator
  labels:
    app: observation-translator
    solution: anomaly
  annotations:
    solution.metadata/chart: "observation-translator"
    solution.metadata/component: "observation-translator"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: observation-translator
  template:
    metadata:
      labels:
        app: observation-translator
        solution: anomaly
      annotations:
        checksum/config: ad6484a0ff247d603f631200a8d299f6676a03f76922e8563f17e5d3336a7e62
    spec:
      containers:
        - name: observation-translator
          image: ${ANOMALY_HOST_IMAGE}
          args:
            - /etc/solution/config/site.conf
          env:
            - name: OBSERVATIONTRANSLATOR
              valueFrom:
                configMapKeyRef:
                  name: observation-translator-cm
                  key: observationTranslator
            - name: HEALTH
              valueFrom:
                configMapKeyRef:
                  name: observation-translator-cm
                  key: health
          ports:
            - name: health
              containerPort: 3000
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
            initialDelaySeconds: 10
            periodSeconds: 6
            failureThreshold: 10
          resources:
            requests:
              cpu: "300m"
              memory: "100Mi"
            limits:
              cpu: "300m"
              memory: "100Mi"
          volumeMounts:
            - name: solution-config
              mountPath: /etc/solution/config
              readOnly: true
      volumes:
        - name: solution-config
          configMap:
            name: observation-translator-cm
            items:
              - key: site.conf
                path: site.conf
