# bash completion for sdl, generated by 'sdl completion bash' from the
# command tree of the generating binary. DO NOT EDIT: the script is
# static, so regenerate it after upgrading sdl.
#
# Wiring (see 'sdl help completion'):
#
#	sdl completion bash > ~/.sdl-completion.bash
#	echo 'source ~/.sdl-completion.bash' >> ~/.bashrc

# _sdl_reply offers the candidate words that match the word under the
# cursor.
_sdl_reply() {
	COMPREPLY=($(compgen -W "$*" -- "$cur"))
}

_sdl() {
	local cur=${COMP_WORDS[COMP_CWORD]}
	COMPREPLY=()
	if [ "$COMP_CWORD" -eq 1 ]; then
		_sdl_reply help pack pick tool wait
		return
	fi
	case ${COMP_WORDS[1]} in
	help) _sdl_help ;;
	pack) _sdl_pack ;;
	pick) _sdl_pick ;;
	tool) _sdl_tool ;;
	esac
}

# sdl pack
_sdl_pack() {
	case $cur in
	-*) _sdl_reply -force -o -tag ;;
	esac
}

# sdl pick
_sdl_pick() {
	if [ "$COMP_CWORD" -eq 2 ]; then
		_sdl_reply red green
	fi
}

# sdl tool
_sdl_tool() {
	if [ "$COMP_CWORD" -eq 2 ]; then
		_sdl_reply info run
		return
	fi
	case ${COMP_WORDS[2]} in
	run) _sdl_tool_run ;;
	esac
}

# sdl tool run
_sdl_tool_run() {
	case $cur in
	-*) _sdl_reply -n ;;
	esac
}

# sdl help
_sdl_help() {
	if [ "$COMP_CWORD" -eq 2 ]; then
		_sdl_reply pack pick tool wait
		return
	fi
	case ${COMP_WORDS[2]} in
	tool) _sdl_help_tool ;;
	esac
}

# sdl help tool
_sdl_help_tool() {
	if [ "$COMP_CWORD" -eq 3 ]; then
		_sdl_reply info run
	fi
}

# Filename completion is the fallback wherever the tree offers no
# words (-o default): solution directories, image files.
complete -o default -F _sdl sdl
