#compdef sdl
# zsh completion for sdl, generated by 'sdl completion zsh' from the
# command tree of the generating binary. DO NOT EDIT: the script is
# static, so regenerate it after upgrading sdl.
#
# Install as _sdl in any $fpath directory for compinit to find, or
# source it directly after compinit has run (see 'sdl help
# completion').

_sdl() {
	if (( CURRENT == 2 )); then
		local -a commands
		commands=(
			'help:show documentation for a command'
			'pack:pack a directory'\''s material'
			'pick:pick a color'
			'tool:toolbox of subcommands'
			'wait:wait for nothing in particular'
		)
		_describe -t commands 'sdl command' commands
		return
	fi
	case $words[2] in
	help) shift words; (( CURRENT-- )); _sdl_help ;;
	pack) shift words; (( CURRENT-- )); _sdl_pack ;;
	pick) shift words; (( CURRENT-- )); _sdl_pick ;;
	tool) shift words; (( CURRENT-- )); _sdl_tool ;;
	wait) shift words; (( CURRENT-- )); _sdl_wait ;;
	esac
}

# sdl pack
_sdl_pack() {
	_arguments \
		'-force[overwrite what'\''s already there]' \
		'-o[write the archive to file instead of stdout]:file:_files' \
		'*-tag[attach one name=value tag (repeatable)]:name=value' \
		'*:file:_files'
}

# sdl pick
_sdl_pick() {
	_arguments ':argument:(red green)'
}

# sdl tool
_sdl_tool() {
	if (( CURRENT == 2 )); then
		local -a commands
		commands=(
			'info:print a tool'\''s description'
			'run:run a tool'
		)
		_describe -t commands 'sdl tool command' commands
		return
	fi
	case $words[2] in
	info) shift words; (( CURRENT-- )); _sdl_tool_info ;;
	run) shift words; (( CURRENT-- )); _sdl_tool_run ;;
	esac
}

# sdl tool info
_sdl_tool_info() {
	_arguments '*:file:_files'
}

# sdl tool run
_sdl_tool_run() {
	_arguments \
		'-n[repeat N times]:N' \
		'*:file:_files'
}

# sdl wait
_sdl_wait() {
	_message 'no arguments'
}

# sdl help
_sdl_help() {
	if (( CURRENT == 2 )); then
		local -a commands
		commands=(
			'pack:pack a directory'\''s material'
			'pick:pick a color'
			'tool:toolbox of subcommands'
			'wait:wait for nothing in particular'
		)
		_describe -t commands 'sdl help topic' commands
		return
	fi
	case $words[2] in
	tool) shift words; (( CURRENT-- )); _sdl_help_tool ;;
	esac
}

# sdl help tool
_sdl_help_tool() {
	if (( CURRENT == 2 )); then
		local -a commands
		commands=(
			'info:print a tool'\''s description'
			'run:run a tool'
		)
		_describe -t commands 'sdl help topic' commands
		return
	fi
}

# The autoload form doubles as a sourceable script: compinit runs the
# file as the _sdl function itself, and a direct source registers the
# completer instead.
if [ "$funcstack[1]" = "_sdl" ]; then
	_sdl "$@"
else
	compdef _sdl sdl
fi
